namespace EpicorWeb.Models
{
	public class VinamJobTracker
	{
		public string JobNum { get; set; }
		public decimal ActSetupHours { get; set; }
		public int OprSeq { get; set; }
		public string OpCode { get; set; }
		public string OpDesc { get; set; }
		public bool SubContract { get; set; }
		public decimal RunQty { get; set; }
		public decimal QtyCompleted { get; set; }
		public decimal EstSetHours { get; set; }
		public bool OpComplete { get; set; }
		public DateTime StartDate { get; set; }
		public decimal EstProdHours { get; set; }
		public DateTime DueDate { get; set; }
		public decimal ActProdHours { get; set; }
		public decimal ActLabCost { get; set; }
		public decimal ActBurCost { get; set; }
		public decimal EstSetHoursPerMch { get; set; }
		public int SetUpCrewSize { get; set; }
		public int ProdCrewSize { get; set; }
		public decimal ProdLabRate { get; set; }
		public decimal SetupLabRate { get; set; }
		public decimal QtyPer { get; set; }
		public decimal ProdStandard { get; set; }
		public decimal OpsPerPart { get; set; }
		public decimal FAQty { get; set; }
		public bool AddedOper { get; set; }
		public int Machines { get; set; }
		public int FSJobStatus { get; set; }
		public string Instructions { get; set; }
		public string ProdUOM { get; set; }
		public string GeneralPlanInfo { get; set; }
		public string EstStdDescription { get; set; }
		public bool JDFOpCompleted { get; set; }
		public bool RemovedfromPlan { get; set; }
		public int EstStdType { get; set; }
		public bool ExternalMES { get; set; }
		public decimal PctReg { get; set; }
		public decimal SetupMaterial { get; set; }
		public int MaterialColorRating { get; set; }
		public string MiscInfo1 { get; set; }
		public string MiscInfo2 { get; set; }
		public string SetupURL { get; set; }
		public decimal ExpPctUp { get; set; }
		public decimal ExpCycTm { get; set; }
		public bool ExpGood { get; set; }
		public bool NonProdLimit { get; set; }
		public bool AutoSpcEnable { get; set; }
		public decimal AutoSpcPeriod { get; set; }
		public bool PartQualEnable { get; set; }
		public int AutoSpcSubgroup { get; set; }
		public bool MobileOperation { get; set; }
		public bool ReWork { get; set; }
		public bool RequestMove { get; set; }
		public decimal BookedUnitCost { get; set; }
		public string UserMapData { get; set; }
		public bool RoughCutSched { get; set; }
		public string SchedComment { get; set; }
		public string ContractID { get; set; }
		public string PrinterID { get; set; }
		public DateTime LastPrintedDate { get; set; }
		public string LastPCIDPrinted { get; set; }
		public string CurrentPkgCode { get; set; }
		public bool ExternalMESSyncRequired { get; set; }
		public DateTime ExternalMESLastSync { get; set; }
		public decimal QtyPerCycle { get; set; }
		public decimal Weight { get; set; }
		public string WeightUOM { get; set; }
		public DateTime TearDwnEndDate { get; set; }
		public decimal TearDwnEndHour { get; set; }
		public string SendAheadType { get; set; }
		public DateTime WITearDwnEndDate { get; set; }
		public decimal SendAheadOffset { get; set; }
		public decimal WITearDwnEndHour { get; set; }
		public bool UseAllRoles { get; set; }
		public string AssetPartNum { get; set; }
		public string SerialNumber { get; set; }
		public bool SNRequiredOpr { get; set; }
		public bool SNRequiredSubConShip { get; set; }
		public string PricePerCode { get; set; }
		public string SalesUM { get; set; }
		public decimal SellingFactor { get; set; }
	}

}
